name: CI

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Action to checkout your repository's code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use Node.js version 14.x or your preferred version

      - name: Install dependencies
        run: npm install # Install project dependencies

      - name: Run tests with Jest
        run: npm test # Replace with your test command

